### ISSUE TITLE
install error 

### ISSUE THREAD

**Issue by hieroo** [neatlogic/neatlogic-itom-all#5]
fatal: remote error: upload-pack: not our ref 7982c3a2cf94883d60804c4511263daaf0b05f14
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'neatlogic-web', but it did not contain 7982c3a2cf94883d60804c4511263daaf0b05f14. Direct fetching of that commit failed.

**Comment by zenkiray** [comment]
try again
